"""rename table rehearsals

Revision ID: b3d03d849914
Revises: b9f2e28ac80b
Create Date: 2023-12-18 21:39:30.467360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3d03d849914'
down_revision: Union[str, None] = 'b9f2e28ac80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rehearsals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_from', sa.TIMESTAMP(), nullable=False),
    sa.Column('time_to', sa.TIMESTAMP(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('required_istruments', sa.Column('rehearsal_id', sa.Integer(), nullable=True))
    op.drop_constraint('required_istruments_request_id_fkey', 'required_istruments', type_='foreignkey')
    op.create_foreign_key(None, 'required_istruments', 'rehearsals', ['rehearsal_id'], ['id'])
    op.drop_column('required_istruments', 'request_id')
    op.drop_table('requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('required_istruments', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'required_istruments', type_='foreignkey')
    op.create_foreign_key('required_istruments_request_id_fkey', 'required_istruments', 'requests', ['request_id'], ['id'])
    op.drop_column('required_istruments', 'rehearsal_id')
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('time_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='requests_room_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='requests_pkey')
    )
    op.drop_table('rehearsals')
    # ### end Alembic commands ###
