"""add instruments types

Revision ID: 502191b52a02
Revises: 7c109e20e783
Create Date: 2023-12-18 23:31:22.992688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502191b52a02'
down_revision: Union[str, None] = '7c109e20e783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('instruments', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instruments', 'instrument_types', ['type_id'], ['id'])
    op.drop_column('instruments', 'type')
    op.add_column('required_istruments', sa.Column('instrument_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'required_istruments', 'instruments', ['instrument_id'], ['id'])
    op.drop_column('required_istruments', 'instrument_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('required_istruments', sa.Column('instrument_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'required_istruments', type_='foreignkey')
    op.drop_column('required_istruments', 'instrument_id')
    op.add_column('instruments', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'instruments', type_='foreignkey')
    op.drop_column('instruments', 'type_id')
    op.drop_table('instrument_types')
    # ### end Alembic commands ###
